# YAML configuration script

data:
  instrument: "APOGEE"
  data_path: "APOGEE_DATA/"
  data_ID: "2M03425325+2326495"

outdir : output/

plotdir : plots/

model:
  grid_name: "PHOENIX"
  parname: ["temp", "logg", "z"]
  parrange: [[2300, 3300], [4.0, 5.0], [-1.0, 1.0]]
  wl_range: [14900, 17100] #angstroms

# Initial parameters for MCMC
Theta :
    grid: [3500., 4.50, 0.0]
    rv: -4.77
    vsini: 5.79
    alpha: 1.0

# Step parameters for MCMC
Theta :
    grid: [1., .01, .01]
    rv: .1
    vsini: .1
    alpha: .001

