# Instrument specifications
data:
  instrument: "APOGEE"
  data_path: "default" # defaults to $APOGEE_DATA path (see setup documentation), unless otherwise specified
  ID: "2M03425325+2326495"
  orders: [[15140,15800],[15860,16425],[16475,16945]]
  visit: 1

# Make sure this config.yaml file is placed in your input directory
workdir: 
  input: "/home/jess/Desktop/Research/FAST/model_tests/test_output"
  output: "/home/jess/Desktop/Research/FAST/model_tests/test_output"

# Specify which parameters will be sampled by MCMC
# otherwise parameters will be fixed at 'init' values
grid:
  grid_name: "PHOENIX"
  parname: ['teff', 'logg', 'fe_h', 'rv', 'vsini', 'alpha']
  # plotname: ['$T_{\rm eff}$', 'logg', '[Fe/H]', 'rv', 'vsini', '$\alpha$']

# MCMC tuning
mcmc:
  nwalkers: 50
  nsteps: 1000
  
# Initial parameters for MCMC
init:
  teff: 3500
  logg: 4.50
  fe_h: 0.0
  rv: -4.77
  vsini: 5.79
  alpha: 1.0

# Step parameters for MCMC
step:
  teff: 1
  logg: .01
  fe_h: .01
  rv: .1
  vsini: .1
  alpha: .001

# Prior ranges for MCMC
prior:
  teff: [2500, 5500]
  logg: [0.0, 5.5]
  fe_h: [-1.0, 1.0]
  rv: [-200, 200]
  vsini: [0, 200]
  alpha: [0, 5]
