# YAML configuration script

data:
  instrument: "APOGEE"
  data_path: "APOGEE_DATA/"
  ID: "2M03425325+2326495"
  wl_range: [14900, 17100] #angstroms
  visit: 1

workdir: "/home/jess/Desktop/Research/FAST/model_tests/test_output"

grid:
  grid_name: "PHOENIX"
  parname: ['teff', 'logg', 'fe_h', 'rv', 'vsini', 'alpha']
  
# Initial parameters for MCMC
init:
    teff: 3500
    logg: 4.50
    fe_h: 0.0
    rv: -4.77
    vsini: 5.79
    alpha: 1.0

# Step parameters for MCMC
step:
    teff: 1
    logg: .01
    fe_h: .01
    rv: .1
    vsini: .1
    alpha: .001
